from __future__ import annotations

import functools
import hashlib
import logging
from contextvars import Token
from dataclasses import dataclass, field
from datetime import timedelta
from typing import (
    TYPE_CHECKING,
    Any,
    Concatenate,
    Generic,
    TypeVar as TypingTypeVar,
    ParamSpec,
    TypeVar,
    cast,
    overload,
)

from .async_tools import (
    assert_async_callable,
    get_callable_name,
    invoke_callable_with_optional_context,
)
from .config import (
    BatchedInput,
    CallbackConfig,
    ChildConfig,
    InvokeConfig,
    MapConfig,
    ParallelBranch,
    ParallelConfig,
    WaitForConditionConfig,
    StepConfig,
    WaitForCallbackConfig,
    WithRetryConfig,
    duration_to_seconds,
)
from .config import RetryStrategyBuilder
from .exceptions import CallbackError, SuspendExecution, ValidationError
from .logger import get_current_context, reset_current_context, set_current_context
from .models import CallbackTimeoutType, OperationSubType, OperationIdentifier
from .serdes import PassThroughSerDes, SerDes, deserialize
from .state import ExecutionState
from .types import (
    Context,
    Callback as CallbackProtocol,
    DurableContext as DurableContextProtocol,
)
from .types import StepContext, WaitForCallbackContext, WaitForConditionCheckContext

if TYPE_CHECKING:
    from collections.abc import Awaitable, Callable, Sequence

    from .models import BatchResult
    from .state import CheckpointedResult
    from .types import LambdaContext

P = TypeVar("P")  # Payload type
R = TypeVar("R")  # Result type
T = TypeVar("T")
U = TypeVar("U")
Params = ParamSpec("Params")


logger = logging.getLogger(__name__)

PASS_THROUGH_SERDES: SerDes[Any] = PassThroughSerDes()
ContextType = TypingTypeVar(
    "ContextType",
    StepContext,
    WaitForCallbackContext,
    WaitForConditionCheckContext,
)


def get_context() -> Context:
    """Return the current execution context."""
    current_context = get_current_context()
    if current_context is None:
        msg = (
            "get_context() can only be used while a durable function, step "
            "function, wait_for_callback submitter, or wait_for_condition check "
            "is executing."
        )
        raise RuntimeError(msg)
    return current_context


def _get_context_as(
    context_type: type[ContextType],
    message: str,
) -> ContextType:
    current_context = get_current_context()
    if current_context is None or not isinstance(current_context, context_type):
        raise RuntimeError(message)
    return current_context


def get_attempt() -> int | None:
    current_context = _get_context_as(
        StepContext,
        "get_attempt() can only be used while a step function is executing.",
    )
    return current_context.attempt


def _set_context(context: Context) -> Token[Context | None]:
    return set_current_context(context)


def _reset_context(token: Token[Context | None]) -> None:
    reset_current_context(token)


def _get_durable_context(operation_name: str) -> DurableContext:
    current_context = get_context()
    if isinstance(
        current_context,
        (StepContext, WaitForCallbackContext, WaitForConditionCheckContext),
    ):
        msg = (
            f"{operation_name}() can only be used while a durable function or child "
            "context is executing."
        )
        raise RuntimeError(msg)
    return cast(DurableContext, current_context)


class StepCounter:
    def __init__(self, prefix: str | None) -> None:
        self._prefix = prefix
        self._value = 0

    def increment(self) -> int:
        self._value += 1
        return self._value

    def get_current(self) -> int:
        return self._value

    def _create_step_id_for_logical_step(self, step: int) -> str:
        """
        Generate a step_id based on the given logical step.
        This allows us to recover operation ids or even look
        forward without changing the internal state of this context.
        """
        prefix: str | None = self._prefix
        step_id: str = f"{prefix}-{step}" if prefix else str(step)
        return hashlib.blake2b(step_id.encode()).hexdigest()[:64]

    def create_step_id(self) -> str:
        """Generate a step id, incrementing in order of invocation.

        This method is an internal implementation detail. Do not rely the exact format of
        the id generated by this method. It is subject to change without notice.
        """
        new_counter: int = self.increment()
        return self._create_step_id_for_logical_step(new_counter)


from .operation.callback import CallbackOperationExecutor, wait_for_callback_handler
from .operation.child import child_handler
from .operation.invoke import InvokeOperationExecutor
from .operation.map import map_handler
from .operation.parallel import parallel_handler
from .operation.step import StepOperationExecutor
from .operation.wait import WaitOperationExecutor
from .operation.wait_for_condition import WaitForConditionOperationExecutor


def _format_callback_error_message(checkpointed_result: CheckpointedResult) -> str:
    """Build a stable callback error message from checkpoint state."""
    error = checkpointed_result.error
    if not error or not error.message:
        return "Callback failed"

    message = error.message
    if (
        checkpointed_result.is_timed_out()
        and error.type in {timeout.value for timeout in CallbackTimeoutType}
        and error.type not in message
    ):
        return f"{message}: {error.type}"

    return message


def _resolve_operation_name(name: str | None, func: Callable) -> str | None:
    """Return explicit name or a stable callable-derived fallback."""
    return name or get_callable_name(func)


async def _create_callback_in_context(
    context: DurableContext,
    name: str | None = None,
    config: CallbackConfig | None = None,
) -> Callback:
    if not config:
        config = CallbackConfig()
    operation_id: str = context._step_counter.create_step_id()

    executor: CallbackOperationExecutor = CallbackOperationExecutor(
        state=context.state,
        operation_identifier=OperationIdentifier(
            operation_id=operation_id,
            sub_type=OperationSubType.CALLBACK,
            parent_id=context.parent_id,
            name=name,
        ),
        config=config,
    )
    callback_id: str = await executor.process()
    result: Callback = Callback(
        callback_id=callback_id,
        operation_id=operation_id,
        state=context.state,
        serdes=config.serdes,
    )
    context.state.track_replay(operation_id=operation_id)
    return result


async def _invoke_in_context(
    context: DurableContext,
    function_name: str,
    payload: P,
    name: str | None = None,
    config: InvokeConfig[P, R] | None = None,
) -> R:
    if not config:
        config = InvokeConfig[P, R]()
    operation_id = context._step_counter.create_step_id()

    executor: InvokeOperationExecutor[R] = InvokeOperationExecutor(
        function_name=function_name,
        payload=payload,
        state=context.state,
        operation_identifier=OperationIdentifier(
            operation_id=operation_id,
            sub_type=OperationSubType.CHAINED_INVOKE,
            parent_id=context.parent_id,
            name=name,
        ),
        config=config,
    )
    result: R = await executor.process()
    context.state.track_replay(operation_id=operation_id)
    return result


async def _map_in_context(
    context: DurableContext,
    inputs: Sequence[U],
    func: Callable[[U | BatchedInput[Any, U], int, Sequence[U]], Awaitable[T]],
    name: str | None = None,
    config: MapConfig | None = None,
) -> BatchResult[T]:
    assert_async_callable(func)
    map_name: str | None = _resolve_operation_name(name, func)

    operation_id = context._step_counter.create_step_id()
    operation_identifier = OperationIdentifier(
        operation_id=operation_id,
        sub_type=OperationSubType.MAP,
        parent_id=context.parent_id,
        name=map_name,
    )
    map_context = context.create_child_context(operation_id=operation_id)

    async def map_in_child_context() -> BatchResult[T]:
        return await map_handler(
            items=inputs,
            func=func,
            config=config,
            execution_state=context.state,
            map_context=map_context,
            operation_identifier=operation_identifier,
        )

    result = await child_handler(
        func=map_in_child_context,
        state=context.state,
        operation_identifier=operation_identifier,
        config=ChildConfig(
            sub_type=OperationSubType.MAP,
            serdes=getattr(config, "serdes", None),
            item_serdes=None,
        ),
    )
    context.state.track_replay(operation_id=operation_id)
    return result


async def _parallel_in_context(
    context: DurableContext,
    functions: Sequence[Callable[[], Awaitable[T]] | ParallelBranch[T]],
    name: str | None = None,
    config: ParallelConfig | None = None,
) -> BatchResult[T]:
    for index, function in enumerate(functions):
        target = function.func if isinstance(function, ParallelBranch) else function
        assert_async_callable(target, label=f"functions[{index}]")

    operation_id = context._step_counter.create_step_id()
    parallel_context = context.create_child_context(operation_id=operation_id)
    operation_identifier = OperationIdentifier(
        operation_id=operation_id,
        sub_type=OperationSubType.PARALLEL,
        parent_id=context.parent_id,
        name=name,
    )

    async def parallel_in_child_context() -> BatchResult[T]:
        return await parallel_handler(
            callables=functions,
            config=config,
            execution_state=context.state,
            parallel_context=parallel_context,
            operation_identifier=operation_identifier,
        )

    result = await child_handler(
        func=parallel_in_child_context,
        state=context.state,
        operation_identifier=operation_identifier,
        config=ChildConfig(
            sub_type=OperationSubType.PARALLEL,
            serdes=getattr(config, "serdes", None),
            item_serdes=None,
        ),
    )
    context.state.track_replay(operation_id=operation_id)
    return result


async def _run_in_child_context_in_context(
    context: DurableContext,
    func: Callable[[], Awaitable[T]],
    name: str | None = None,
    config: ChildConfig | None = None,
) -> T:
    assert_async_callable(func)
    step_name: str | None = _resolve_operation_name(name, func)
    operation_id = context._step_counter.create_step_id()
    sub_type = (
        config.sub_type
        if config and config.sub_type
        else OperationSubType.RUN_IN_CHILD_CONTEXT
    )

    is_virtual: bool = config.is_virtual if config else False
    child_context = context.create_child_context(
        operation_id=operation_id,
        is_virtual=is_virtual,
    )

    async def callable_with_child_context():
        return await child_context._invoke_user_callable(
            func,
            context_position="prepend",
        )

    result = await child_handler(
        func=callable_with_child_context,
        state=context.state,
        operation_identifier=OperationIdentifier(
            operation_id=operation_id,
            sub_type=sub_type,
            parent_id=context.parent_id,
            name=step_name,
        ),
        config=config,
    )
    context.state.track_replay(operation_id=operation_id)
    return result


async def _step_in_context(
    context: DurableContext,
    func: Callable[[], Awaitable[T]],
    name: str | None = None,
    config: StepConfig | None = None,
) -> T:
    assert_async_callable(func)
    step_name = name or get_callable_name(func, include_original_name=False)
    logger.debug("Step name: %s", step_name)
    if not config:
        config = StepConfig()
    operation_id = context._step_counter.create_step_id()

    executor: StepOperationExecutor[T] = StepOperationExecutor(
        func=func,
        config=config,
        state=context.state,
        operation_identifier=OperationIdentifier(
            operation_id=operation_id,
            sub_type=OperationSubType.STEP,
            parent_id=context.parent_id,
            name=step_name,
        ),
    )
    result: T = await executor.process()
    context.state.track_replay(operation_id=operation_id)
    return result


async def _wait_in_context(
    context: DurableContext,
    duration: timedelta,
    name: str | None = None,
) -> None:
    seconds = duration_to_seconds(duration)
    if seconds < 1:
        msg = "duration must be at least 1 second"
        raise ValidationError(msg)
    operation_id = context._step_counter.create_step_id()

    executor: WaitOperationExecutor = WaitOperationExecutor(
        seconds=seconds,
        state=context.state,
        operation_identifier=OperationIdentifier(
            operation_id=operation_id,
            sub_type=OperationSubType.WAIT,
            parent_id=context.parent_id,
            name=name,
        ),
    )
    await executor.process()
    context.state.track_replay(operation_id=operation_id)


async def _wait_for_callback_in_context(
    context: DurableContext,
    submitter: Callable[[str], Awaitable[Any]],
    name: str | None = None,
    config: WaitForCallbackConfig | None = None,
) -> Any:
    assert_async_callable(submitter, label="submitter")
    step_name: str | None = _resolve_operation_name(name, submitter)
    logger.debug("wait_for_callback name: %s", step_name)

    async def wait_in_child_context():
        current_context = get_context()
        return await wait_for_callback_handler(
            current_context,
            submitter,
            step_name,
            config,
        )

    return await context.run_in_child_context(
        wait_in_child_context,
        step_name,
    )


async def _wait_for_condition_in_context(
    context: DurableContext,
    check: Callable[[T], Awaitable[T]],
    config: WaitForConditionConfig[T],
    name: str | None = None,
) -> T:
    if check is None:
        msg = "`check` is required for wait_for_condition"
        raise ValidationError(msg)
    if not config:
        msg = "`config` is required for wait_for_condition"
        raise ValidationError(msg)
    assert_async_callable(check, label="check")

    operation_id = context._step_counter.create_step_id()
    executor: WaitForConditionOperationExecutor[T] = WaitForConditionOperationExecutor(
        check=check,
        config=config,
        state=context.state,
        operation_identifier=OperationIdentifier(
            operation_id=operation_id,
            sub_type=OperationSubType.WAIT_FOR_CONDITION,
            parent_id=context.parent_id,
            name=name,
        ),
    )
    result: T = await executor.process()
    context.state.track_replay(operation_id=operation_id)
    return result


async def create_callback(
    name: str | None = None, config: CallbackConfig | None = None
) -> Callback:
    context = _get_durable_context("create_callback")
    if isinstance(context, DurableContext):
        return await _create_callback_in_context(
            context,
            name=name,
            config=config,
        )
    return await context.create_callback(name=name, config=config)


async def invoke(
    function_name: str,
    payload: P,
    name: str | None = None,
    config: InvokeConfig[P, R] | None = None,
) -> R:
    context = _get_durable_context("invoke")
    if isinstance(context, DurableContext):
        return await _invoke_in_context(
            context,
            function_name=function_name,
            payload=payload,
            name=name,
            config=config,
        )
    return await context.invoke(
        function_name=function_name,
        payload=payload,
        name=name,
        config=config,
    )


async def map(
    inputs: Sequence[U],
    func: Callable[[U | BatchedInput[Any, U], int, Sequence[U]], Awaitable[T]],
    name: str | None = None,
    config: MapConfig | None = None,
):
    context = _get_durable_context("map")
    if isinstance(context, DurableContext):
        return await _map_in_context(
            context,
            inputs=inputs,
            func=func,
            name=name,
            config=config,
        )
    return await context.map(inputs=inputs, func=func, name=name, config=config)


async def parallel(
    functions: Sequence[Callable[[], Awaitable[T]] | ParallelBranch[T]],
    name: str | None = None,
    config: ParallelConfig | None = None,
):
    context = _get_durable_context("parallel")
    if isinstance(context, DurableContext):
        return await _parallel_in_context(
            context,
            functions=functions,
            name=name,
            config=config,
        )
    return await context.parallel(functions=functions, name=name, config=config)


async def run_in_child_context(
    func: Callable[[], Awaitable[T]],
    name: str | None = None,
    config: ChildConfig | None = None,
) -> T:
    context = _get_durable_context("run_in_child_context")
    if isinstance(context, DurableContext):
        return await _run_in_child_context_in_context(
            context,
            func=func,
            name=name,
            config=config,
        )
    return await context.run_in_child_context(func=func, name=name, config=config)


async def step(
    func: Callable[[], Awaitable[T]],
    name: str | None = None,
    config: StepConfig | None = None,
) -> T:
    context = _get_durable_context("step")
    if isinstance(context, DurableContext):
        return await _step_in_context(
            context,
            func=func,
            name=name,
            config=config,
        )
    return await context.step(func=func, name=name, config=config)


async def wait(duration: timedelta, name: str | None = None) -> None:
    context = _get_durable_context("wait")
    if isinstance(context, DurableContext):
        await _wait_in_context(context, duration=duration, name=name)
        return
    await context.wait(duration=duration, name=name)


async def wait_for_callback(
    submitter: Callable[[str], Awaitable[Any]],
    name: str | None = None,
    config: WaitForCallbackConfig | None = None,
) -> Any:
    context = _get_durable_context("wait_for_callback")
    if isinstance(context, DurableContext):
        return await _wait_for_callback_in_context(
            context,
            submitter=submitter,
            name=name,
            config=config,
        )
    return await context.wait_for_callback(
        submitter=submitter,
        name=name,
        config=config,
    )


async def wait_for_condition(
    check: Callable[[T], Awaitable[T]],
    config: WaitForConditionConfig[T],
    name: str | None = None,
) -> T:
    context = _get_durable_context("wait_for_condition")
    if isinstance(context, DurableContext):
        return await _wait_for_condition_in_context(
            context,
            check=check,
            config=config,
            name=name,
        )
    return await context.wait_for_condition(check=check, config=config, name=name)


@overload
async def with_retry(
    context: DurableContext,
    func: Callable[[int], Awaitable[T]],
    config: WithRetryConfig[T],
    name: str | None = None,
) -> T: ...


@overload
async def with_retry(
    context: Callable[[int], Awaitable[T]],
    func: WithRetryConfig[T],
    config: None = None,
    name: str | None = None,
) -> T: ...


async def with_retry(
    context: DurableContext | Callable[[int], Awaitable[T]],
    func: Callable[[int], Awaitable[T]] | WithRetryConfig[T],
    config: WithRetryConfig[T] | None = None,
    name: str | None = None,
) -> T:
    """Retry a block of durable logic with configurable backoff."""

    resolved_context: DurableContext
    resolved_func: Callable[[int], Awaitable[T]]
    resolved_config: WithRetryConfig[T]

    if config is None:
        if not callable(context) or not isinstance(func, WithRetryConfig):
            msg = (
                "with_retry() expects either "
                "(context, func, config, name=...) or (func, config, name=...)."
            )
            raise TypeError(msg)
        current_context = get_context()
        if isinstance(current_context, StepContext):
            msg = "with_retry() must run inside a durable context."
            raise RuntimeError(msg)
        resolved_context = cast(DurableContext, current_context)
        resolved_func = cast("Callable[[int], Awaitable[T]]", context)
        resolved_config = func
    else:
        resolved_context = cast(DurableContext, context)
        resolved_func = cast("Callable[[int], Awaitable[T]]", func)
        resolved_config = config

    async def run_loop(*_ignored_args) -> T:
        assert_async_callable(resolved_func)
        try:
            ctx = get_context()
        except RuntimeError:
            if not _ignored_args:
                raise
            ctx = _ignored_args[0]
        if isinstance(ctx, StepContext):
            msg = "with_retry() must run inside a durable context."
            raise RuntimeError(msg)
        durable_ctx = cast(DurableContext, ctx)
        retry_strategy = (
            resolved_config.retry_strategy or RetryStrategyBuilder().build()
        )
        attempt = 0
        while True:
            attempt += 1
            try:
                invoke_with_context = getattr(
                    durable_ctx, "_invoke_user_callable", None
                )
                if invoke_with_context is not None:
                    return await invoke_with_context(
                        resolved_func,
                        attempt,
                        context_position="prepend",
                    )
                return await invoke_callable_with_optional_context(
                    resolved_func,
                    durable_ctx,
                    attempt,
                    context_position="prepend",
                )
            except SuspendExecution:
                raise
            except Exception as err:
                decision = retry_strategy(err, attempt)
                if not decision.should_retry:
                    raise
                wait_name = f"{name}-backoff-{attempt}" if name else None
                if isinstance(durable_ctx, DurableContext):
                    await _wait_in_context(
                        durable_ctx,
                        duration=decision.delay,
                        name=wait_name,
                    )
                else:
                    await durable_ctx.wait(duration=decision.delay, name=wait_name)

    if resolved_config.wrap_with_run_in_child_context:
        if isinstance(resolved_context, DurableContext):
            return await _run_in_child_context_in_context(
                resolved_context,
                run_loop,
                name=name,
                config=resolved_config.child_context_config,
            )
        return await resolved_context.run_in_child_context(
            run_loop,
            name=name,
            config=resolved_config.child_context_config,
        )

    invoke_with_context = getattr(resolved_context, "_invoke_user_callable", None)
    if invoke_with_context is not None:
        return await invoke_with_context(run_loop)

    token = _set_context(resolved_context)
    try:
        return await run_loop()
    finally:
        _reset_context(token)


def durable_step(
    func: Callable[Params, Awaitable[T]],
) -> Callable[Params, Callable[[], Awaitable[T]]]:
    """Wrap an async function so calling it returns a zero-argument step callable.

    The returned callable is suitable for passing to `step()` or `context.step()`,
    which keeps durable step creation explicit while avoiding manual `partial(...)`
    wrapping at the callsite.
    """
    assert_async_callable(func)

    @functools.wraps(func)
    def wrapper(
        *args: Params.args, **kwargs: Params.kwargs
    ) -> Callable[[], Awaitable[T]]:
        return functools.partial(func, *args, **kwargs)

    return wrapper


def durable_child_context(
    func: Callable[Params, Awaitable[T]],
) -> Callable[Params, Callable[[], Awaitable[T]]]:
    """Wrap an async function so calling it returns a zero-argument child context callable.

    The returned callable is suitable for passing to `run_in_child_context()`.
    """
    assert_async_callable(func)

    @functools.wraps(func)
    def wrapper(
        *args: Params.args, **kwargs: Params.kwargs
    ) -> Callable[[], Awaitable[T]]:
        return functools.partial(func, *args, **kwargs)

    return wrapper


def durable_parallel_branch(
    name: str | None = None,
) -> Callable[
    [Callable[Params, Awaitable[T]]],
    Callable[Params, ParallelBranch[T]],
]:
    """Wrap your callable into a named ParallelBranch for use with context.parallel().

    This is a decorator factory — call it with an optional name to produce
    the actual decorator.

    Args:
        name: Optional custom name for this branch. When provided, replaces
            the default "parallel-branch-{index}" naming in execution history.
            If None, the function's __name__ is used.

    Example:
        @durable_parallel_branch(name="fetch-user-data")
        async def fetch_user(user_id: str) -> dict:
            ctx = get_context()

            async def load_user() -> dict:
                return {"id": user_id, "name": "Jane"}

            return await ctx.step(load_user, name="load_user")

        @durable_parallel_branch(name="fetch-orders")
        async def fetch_orders(user_id: str) -> list:
            ctx = get_context()

            async def load_orders() -> list:
                return ["order1", "order2"]

            return await ctx.step(load_orders, name="load_orders")

        # Usage in a durable handler:
        results = await context.parallel(
            functions=[fetch_user(user_id), fetch_orders(user_id)],
            name="load-data",
        )
    """

    def decorator(
        func: Callable[Params, Awaitable[T]],
    ) -> Callable[Params, ParallelBranch[T]]:
        assert_async_callable(func)

        def wrapper(*args, **kwargs) -> ParallelBranch[T]:
            async def function_with_arguments(*runtime_args, **runtime_kwargs) -> T:
                current_context = runtime_args[0] if runtime_args else get_context()
                if runtime_kwargs:
                    msg = "Parallel branches do not accept runtime keyword arguments."
                    raise TypeError(msg)
                return await invoke_callable_with_optional_context(
                    func,
                    current_context,
                    *args,
                    context_position="prepend",
                    **kwargs,
                )

            return ParallelBranch(func=function_with_arguments, name=name)

        return wrapper

    return decorator


def durable_wait_for_callback(
    func: Callable[Concatenate[str, Params], Awaitable[T]],
) -> Callable[Params, Callable[[str], Awaitable[T]]]:
    """Wrap your callable into a wait_for_callback submitter function.

    This decorator allows you to define a submitter function with additional
    parameters that will be bound when called.

    Args:
        func: A callable that takes callback_id and additional parameters

    Returns:
        A wrapper function that binds the additional parameters and returns
        a submitter function compatible with wait_for_callback

    Example:
        @durable_wait_for_callback
        async def submit_to_external_system(
            callback_id: str,
            task_name: str,
            priority: int
        ):
            logging.getLogger(__name__).info(
                "Submitting %s with callback %s", task_name, callback_id
            )
            external_api.submit_task(
                task_name=task_name,
                priority=priority,
                callback_id=callback_id
            )

        # Usage in durable handler:
        result = await context.wait_for_callback(
            submit_to_external_system("my_task", priority=5)
        )
    """
    assert_async_callable(func)

    def wrapper(*args, **kwargs):
        async def submitter_with_arguments(callback_id: str):
            return await func(callback_id, *args, **kwargs)

        submitter_with_arguments._original_name = func.__name__  # noqa: SLF001
        return submitter_with_arguments

    return wrapper


class Callback(Generic[T], CallbackProtocol[T]):  # noqa: PYI059
    """A future that will block on result() until callback_id returns."""

    def __init__(
        self,
        callback_id: str,
        operation_id: str,
        state: ExecutionState,
        serdes: SerDes[T] | None = None,
    ):
        self.callback_id: str = callback_id
        self.operation_id: str = operation_id
        self.state: ExecutionState = state
        self.serdes: SerDes[T] | None = serdes

    async def result(self) -> T | None:
        """Return the result of the future. Will block until result is available.

        This will suspend the current execution while waiting for the result to
        become available. Durable Functions will replay the execution once the
        result is ready, and proceed when it reaches the .result() call.

        Use the callback id with the following APIs to send back the result, error or
        heartbeats: SendDurableExecutionCallbackSuccess, SendDurableExecutionCallbackFailure
        and SendDurableExecutionCallbackHeartbeat.
        """
        checkpointed_result: CheckpointedResult = self.state.get_checkpoint_result(
            self.operation_id
        )

        if not checkpointed_result.is_existent():
            msg = "Callback operation must exist"
            raise CallbackError(message=msg, callback_id=self.callback_id)

        if (
            checkpointed_result.is_failed()
            or checkpointed_result.is_cancelled()
            or checkpointed_result.is_timed_out()
            or checkpointed_result.is_stopped()
        ):
            msg = _format_callback_error_message(checkpointed_result)
            raise CallbackError(message=msg, callback_id=self.callback_id)

        if checkpointed_result.is_succeeded():
            if checkpointed_result.result is None:
                return None  # type: ignore

            return deserialize(
                serdes=self.serdes if self.serdes is not None else PASS_THROUGH_SERDES,
                data=checkpointed_result.result,
                operation_id=self.operation_id,
                durable_execution_arn=self.state.durable_execution_arn,
            )

        # operation exists; it has not terminated (successfully or otherwise)
        # therefore we should wait
        msg = "Callback result not received yet. Suspending execution while waiting for result."
        raise SuspendExecution(msg)


@dataclass(eq=False)
class DurableContext(DurableContextProtocol):
    state: ExecutionState
    lambda_context: LambdaContext | None = None
    parent_id: str | None = None
    step_id_prefix: str | None = None
    durable_execution_arn: str = field(init=False)
    _parent_id: str | None = field(init=False, repr=False)
    _step_id_prefix: str | None = field(init=False, repr=False)
    is_virtual: bool = field(init=False)
    _step_counter: StepCounter = field(init=False, repr=False)
    execution_state: ExecutionState = field(init=False)
    execution_arn: str = field(init=False)
    operation_id: str | None = field(init=False)
    operation_name: str | None = field(init=False, default=None)

    def __post_init__(self) -> None:
        self.durable_execution_arn = self.state.durable_execution_arn
        self._parent_id = self.parent_id
        self._step_id_prefix = (
            self.step_id_prefix if self.step_id_prefix is not None else self.parent_id
        )
        self.is_virtual = self.parent_id != self._step_id_prefix
        self._step_counter = StepCounter(self._step_id_prefix)

        self.execution_state = self.state
        self.execution_arn = self.state.durable_execution_arn
        self.operation_id = self.step_id_prefix
        self.operation_name = None

    def create_child_context(
        self, operation_id: str, *, is_virtual: bool = False
    ) -> DurableContext:
        """Create a child context for the given operation."""
        child_parent_id: str | None = self.parent_id if is_virtual else operation_id
        logger.debug(
            "Creating child context for operation %s (is_virtual=%s)",
            operation_id,
            is_virtual,
        )
        return DurableContext(
            state=self.state,
            lambda_context=self.lambda_context,
            parent_id=child_parent_id,
            step_id_prefix=operation_id,
        )

    async def _invoke_user_callable(
        self,
        func: Callable[..., Awaitable[T]],
        *args,
        context_position: str = "prepend",
        **kwargs,
    ) -> T:
        token = _set_context(self)
        try:
            return await invoke_callable_with_optional_context(
                func,
                self,
                *args,
                context_position=context_position,
                **kwargs,
            )
        finally:
            _reset_context(token)

    async def create_callback(
        self, name: str | None = None, config: CallbackConfig | None = None
    ) -> Callback:
        return await _create_callback_in_context(self, name=name, config=config)

    async def invoke(
        self,
        function_name: str,
        payload: P,
        name: str | None = None,
        config: InvokeConfig[P, R] | None = None,
    ) -> R:
        return await _invoke_in_context(
            self,
            function_name=function_name,
            payload=payload,
            name=name,
            config=config,
        )

    async def map(
        self,
        inputs: Sequence[U],
        func: Callable[[U | BatchedInput[Any, U], int, Sequence[U]], Awaitable[T]],
        name: str | None = None,
        config: MapConfig | None = None,
    ) -> BatchResult[T]:
        return await _map_in_context(
            self,
            inputs=inputs,
            func=func,
            name=name,
            config=config,
        )

    async def parallel(
        self,
        functions: Sequence[Callable[[], Awaitable[T]] | ParallelBranch[T]],
        name: str | None = None,
        config: ParallelConfig | None = None,
    ) -> BatchResult[T]:
        return await _parallel_in_context(
            self,
            functions=functions,
            name=name,
            config=config,
        )

    async def run_in_child_context(
        self,
        func: Callable[[], Awaitable[T]],
        name: str | None = None,
        config: ChildConfig | None = None,
    ) -> T:
        return await _run_in_child_context_in_context(
            self,
            func=func,
            name=name,
            config=config,
        )

    async def step(
        self,
        func: Callable[[], Awaitable[T]],
        name: str | None = None,
        config: StepConfig | None = None,
    ) -> T:
        return await _step_in_context(
            self,
            func=func,
            name=name,
            config=config,
        )

    async def wait(self, duration: timedelta, name: str | None = None) -> None:
        await _wait_in_context(self, duration=duration, name=name)

    async def wait_for_callback(
        self,
        submitter: Callable[[str], Awaitable[Any]],
        name: str | None = None,
        config: WaitForCallbackConfig | None = None,
    ) -> Any:
        return await _wait_for_callback_in_context(
            self,
            submitter=submitter,
            name=name,
            config=config,
        )

    async def wait_for_condition(
        self,
        check: Callable[[T], Awaitable[T]],
        config: WaitForConditionConfig[T],
        name: str | None = None,
    ) -> T:
        return await _wait_for_condition_in_context(
            self,
            check=check,
            config=config,
            name=name,
        )
