from __future__ import annotations

import hashlib
from _contextvars import ContextVar
from contextvars import Token


class OperationIdGenerator:
    def __init__(self, prefix: str | None) -> None:
        self._prefix = prefix
        self._counter = 0

    def increment(self) -> int:
        self._counter += 1
        return self._counter

    def get_current(self) -> int:
        return self._counter

    def _create_step_id_for_logical_step(self, step: int) -> str:
        """
        Generate a step_id based on the given logical step.
        This allows us to recover operation ids or even look
        forward without changing the internal state of this context.
        """
        prefix: str | None = self._prefix
        step_id: str = f"{prefix}-{step}" if prefix else str(step)
        return hashlib.blake2b(step_id.encode()).hexdigest()[:64]

    def create_step_id(self) -> str:
        """Generate a step id, incrementing in order of invocation.

        This method is an internal implementation detail. Do not rely the exact format of
        the id generated by this method. It is subject to change without notice.
        """
        new_counter: int = self.increment()
        return self._create_step_id_for_logical_step(new_counter)


_current_context: ContextVar = ContextVar(
    "async_durable_execution.current_context",
    default=None,
)


def set_current_context(context) -> Token:
    return _current_context.set(context)


def reset_current_context(token: Token) -> None:
    _current_context.reset(token)


def get_current_context():
    current_context = _current_context.get()
    if current_context is None:
        msg = (
            "get_context() can only be used while a durable function, step "
            "function, wait_for_callback submitter, or wait_for_condition check "
            "is executing."
        )
        raise RuntimeError(msg)
    return current_context


def get_context():
    """Backward-compatible alias for get_current_context()."""
    return get_current_context()
