"""Implementation for run_in_child_context."""

from __future__ import annotations

import functools
import hashlib
import logging
from contextlib import contextmanager
from dataclasses import dataclass, field
from threading import Lock
from typing import TYPE_CHECKING, TypeVar, cast

from .base import (
    CHECKPOINT_NOT_FOUND,
    CheckpointedResult,
    OperationExecutor,
    OperationContext,
)
from ..async_tools import (
    assert_async_callable,
    invoke_user_callable,
)
from ..context import get_current_context
from ..exceptions import (
    InvocationError,
    SuspendExecution,
)
from ..models import (
    ContextOptions,
    ErrorObject,
    Operation,
    OperationIdentifier,
    OperationStatus,
    OperationSubType,
    OperationUpdate,
)
from ..serdes import deserialize, serialize

if TYPE_CHECKING:
    from collections.abc import Awaitable, Callable

    from ..serdes import SerDes
    from ..state import ExecutionState
    from ..types import SummaryGenerator

logger = logging.getLogger(__name__)

T = TypeVar("T")

# Checkpoint size limit in bytes (256KB)
CHECKPOINT_SIZE_LIMIT = 256 * 1024


class OrphanedChildException(BaseException):
    """Raised when a child operation checkpoints after its parent context completed.

    This inherits from BaseException so user code does not accidentally catch it
    with broad exception handlers like ``except Exception``.
    """

    def __init__(self, message: str, operation_id: str):
        super().__init__(message)
        self.operation_id = operation_id


class OperationIdGenerator:
    """Generate deterministic operation ids within a durable execution scope."""

    def __init__(self, prefix: str | None) -> None:
        self._prefix = prefix
        self._counter = 0

    def increment(self) -> int:
        self._counter += 1
        return self._counter

    def get_current(self) -> int:
        return self._counter

    def _create_step_id_for_logical_step(self, step: int) -> str:
        """
        Generate a step_id based on the given logical step.
        This allows us to recover operation ids or even look
        forward without changing the internal state of this context.
        """
        prefix: str | None = self._prefix
        step_id: str = f"{prefix}-{step}" if prefix else str(step)
        return hashlib.blake2b(step_id.encode()).hexdigest()[:64]

    def create_step_id(self) -> str:
        """Generate a step id, incrementing in order of invocation.

        This method is an internal implementation detail. Do not rely the exact format of
        the id generated by this method. It is subject to change without notice.
        """
        new_counter: int = self.increment()
        return self._create_step_id_for_logical_step(new_counter)


class ChildOperationExecutor(OperationExecutor[T]):
    """Executor for child context operations."""

    def __init__(
        self,
        func: Callable[[], Awaitable[T]],
        state: ExecutionState,
        operation_identifier: OperationIdentifier,
        *,
        serdes: SerDes | None = None,
        summary_generator: SummaryGenerator | None = None,
        is_virtual: bool = False,
    ):
        """Initialize the child operation executor.

        Args:
            func: The child context function to execute
            state: The execution state
            operation_identifier: The operation identifier
            serdes: Optional serializer for the child context result.
            summary_generator: Optional summary generator for large child results.
            is_virtual: Whether this child context should skip lifecycle checkpoints.
        """
        super().__init__(state=state, operation_identifier=operation_identifier)
        self.func = func
        self.serdes = serdes
        self.summary_generator = summary_generator
        self.is_virtual = is_virtual
        self.sub_type = operation_identifier.sub_type

    async def start(self) -> T:
        """Start a new child context operation."""
        if not self.is_virtual:
            start_operation: OperationUpdate = OperationUpdate.create_context_start(
                identifier=self.operation_identifier,
                sub_type=self.sub_type,
            )
            await self.create_checkpoint(start_operation, is_sync=False)

        return await self.execute(CHECKPOINT_NOT_FOUND)

    async def replay(self, operation: Operation) -> T:
        """Replay an existing child context operation from its checkpoint."""
        checkpointed_result = CheckpointedResult.create_from_operation(operation)
        if (
            operation.status is OperationStatus.SUCCEEDED
            and not checkpointed_result.is_replay_children()
        ):
            logger.debug(
                "Child context already completed, skipping execution for id: %s, name: %s",
                self.operation_identifier.operation_id,
                self.operation_name,
            )
            if checkpointed_result.result is None:
                return None  # type: ignore[return-value]

            result: T = await deserialize(
                serdes=self.serdes,
                data=checkpointed_result.result,
                operation_id=self.operation_id,
                durable_execution_arn=self.durable_execution_arn,
            )
            return result

        if (
            operation.status is OperationStatus.SUCCEEDED
            and checkpointed_result.is_replay_children()
        ):
            return await self.execute(checkpointed_result)

        if operation.status is OperationStatus.FAILED:
            checkpointed_result.raise_callable_error()

        return await self.execute(checkpointed_result)

    async def execute(self, checkpointed_result: CheckpointedResult) -> T:
        """Execute child context function with error handling and large payload support.

        Args:
            checkpointed_result: The checkpoint data containing operation state

        Returns:
            The result of executing the child context function

        Raises:
            SuspendExecution: Re-raised without checkpointing
            InvocationError: Re-raised after checkpointing FAIL
            CallableRuntimeError: Raised for other exceptions after checkpointing FAIL
        """
        logger.debug(
            "▶️ Executing child context for id: %s, name: %s",
            self.operation_identifier.operation_id,
            self.operation_identifier.name,
        )
        try:
            # TODO: fix attempt (checkpointed_result.is_existent is always True)
            wrapped_user_func = self.state.wrap_user_function(
                self.func,
                self.operation_identifier,
                checkpointed_result.is_replay_children(),
                attempt=None if checkpointed_result.is_existent() else 1,
            )
            raw_result: T = await wrapped_user_func()

            if self.is_virtual:
                logger.debug(
                    "Virtual context: Exiting child context without creating another checkpoint. id: %s, name: %s",
                    self.operation_identifier.operation_id,
                    self.operation_identifier.name,
                )
                return raw_result

            # If in replay_children mode, return without checkpointing
            if checkpointed_result.is_replay_children():
                logger.debug(
                    "ReplayChildren mode: Executed child context again on replay due to large payload. Exiting child context without creating another checkpoint. id: %s, name: %s",
                    self.operation_identifier.operation_id,
                    self.operation_identifier.name,
                )
                return raw_result

            # Serialize result
            serialized_result: str = await serialize(
                serdes=self.serdes,
                value=raw_result,
                operation_id=self.operation_id,
                durable_execution_arn=self.durable_execution_arn,
            )

            # Check payload size and use ReplayChildren mode if needed
            # Summary Generator Logic:
            # When the serialized result exceeds 256KB, we use ReplayChildren mode to avoid
            # checkpointing large payloads. Instead, we checkpoint a compact summary and mark
            # the operation for replay. This matches the TypeScript implementation behavior.
            #
            # See TypeScript reference:
            # - aws-durable-execution-sdk-js/src/handlers/run-in-child-context-handler/run-in-child-context-handler.ts (lines ~200-220)
            #
            # The summary generator creates a JSON summary with metadata (type, counts, status)
            # instead of the full BatchResult. During replay, the child context is re-executed
            # to reconstruct the full result rather than deserializing from the checkpoint.
            replay_children: bool = False
            if len(serialized_result) > CHECKPOINT_SIZE_LIMIT:
                logger.debug(
                    "Large payload detected, using ReplayChildren mode: id: %s, name: %s, payload_size: %d, limit: %d",
                    self.operation_identifier.operation_id,
                    self.operation_identifier.name,
                    len(serialized_result),
                    CHECKPOINT_SIZE_LIMIT,
                )
                replay_children = True
                # Use summary generator if provided, otherwise use empty string (matches TypeScript)
                serialized_result = (
                    self.summary_generator(raw_result) if self.summary_generator else ""
                )

            # Checkpoint SUCCEED
            success_operation: OperationUpdate = OperationUpdate.create_context_succeed(
                identifier=self.operation_identifier,
                payload=serialized_result,
                sub_type=self.sub_type,
                context_options=ContextOptions(replay_children=replay_children),
            )
            # Checkpoint child context SUCCEED with blocking (is_sync=True, default).
            # Must ensure the child context result is persisted before returning to the parent.
            # This guarantees the result is durable and child operations won't be re-executed on replay
            # (unless replay_children=True for large payloads).
            await self.create_checkpoint(success_operation)

            logger.debug(
                "✅ Successfully completed child context for id: %s, name: %s",
                self.operation_identifier.operation_id,
                self.operation_identifier.name,
            )
            return raw_result  # noqa: TRY300
        except SuspendExecution:
            # Don't checkpoint SuspendExecution - let it bubble up
            raise
        except Exception as e:
            error_object = ErrorObject.from_exception(e)
            # Virtual deliberately does not write checkpoints, but exception still propagates below
            if not self.is_virtual:
                fail_operation: OperationUpdate = OperationUpdate.create_context_fail(
                    identifier=self.operation_identifier,
                    error=error_object,
                    sub_type=self.sub_type,
                )
                # Checkpoint child context FAIL with blocking (is_sync=True, default).
                # Must ensure the failure state is persisted before raising the exception.
                # This guarantees the error is durable and child operations won't be re-executed on replay.
                await self.create_checkpoint(fail_operation)

            # InvocationError and its derivatives can be retried.
            # When we encounter an invocation error (in all of its forms), we
            # bubble that error upwards (with the checkpoint in place for
            # non-virtual) such that we reach the execution handler at the
            # very top, which will then make the backend retry.
            if isinstance(e, InvocationError):
                raise
            raise error_object.to_callable_runtime_error() from e


async def child_handler(
    func: Callable[[], Awaitable[T]],
    state: ExecutionState,
    operation_identifier: OperationIdentifier,
    *,
    serdes: SerDes | None = None,
    item_serdes: SerDes | None = None,
    summary_generator: SummaryGenerator | None = None,
    is_virtual: bool = False,
) -> T:
    """Run a function in a child context.

    Create a ChildOperationExecutor and delegates to its process() method.

    Args:
        func: The child context function to execute.
        state: The execution state.
        operation_identifier: The operation identifier for this child context.
        serdes: Optional serializer for the child context result.
        item_serdes: Optional serializer for child items used by composed operations.
        summary_generator: Optional summary generator for large child results.
        is_virtual: Whether the child context should skip lifecycle checkpoints.

    Returns:
        The result of executing the child context.

    Raises:
        May raise operation-specific errors during execution.
    """
    executor = ChildOperationExecutor(
        func,
        state,
        operation_identifier,
        serdes=serdes,
        summary_generator=summary_generator,
        is_virtual=is_virtual,
    )
    return await executor.process()


@dataclass(frozen=True)
class DurableContext(OperationContext):
    """Runtime context available to a durable handler or child context."""

    step_id_prefix: str | None = None
    replaying: bool = False
    _replay_status_lock: Lock = field(
        default_factory=Lock,
        repr=False,
        compare=False,
    )

    @functools.cached_property
    def step_counter(self):
        return OperationIdGenerator(self.operation_id_generator_prefix)

    @property
    def is_virtual(self) -> bool:
        return self.operation_identifier.parent_id != self.operation_id_generator_prefix

    @property
    def operation_id_generator_prefix(self):
        return (
            self.step_id_prefix
            if self.step_id_prefix is not None
            else self.operation_identifier.parent_id
        )

    def create_child_context(
        self, operation_id: str, *, is_virtual: bool = False
    ) -> DurableContext:
        """Create a child context for the given operation."""
        child_parent_id: str | None = self.parent_id if is_virtual else operation_id
        logger.debug(
            "Creating child context for operation %s (is_virtual=%s)",
            operation_id,
            is_virtual,
        )
        return DurableContext(
            execution_state=self.execution_state,
            operation_identifier=OperationIdentifier(
                operation_id=None,
                sub_type=OperationSubType.EXECUTION,
                parent_id=child_parent_id,
            ),
            lambda_context=self.lambda_context,
            step_id_prefix=operation_id,
            replaying=self.is_replaying(),
        )

    def is_replaying(self) -> bool:
        """Return True while this context is replaying prior operations."""
        with self._replay_status_lock:
            return self.replaying

    def _set_replay_status_new(self) -> None:
        with self._replay_status_lock:
            object.__setattr__(self, "replaying", False)

    def _peek_next_operation_id(self) -> str:
        return self.step_counter._create_step_id_for_logical_step(  # noqa: SLF001
            self.step_counter.get_current() + 1
        )

    def _next_operation_result(self) -> CheckpointedResult:
        operation = self.execution_state.operations.get(self._peek_next_operation_id())
        if isinstance(operation, Operation):
            return CheckpointedResult.create_from_operation(operation)
        if operation is None:
            return CHECKPOINT_NOT_FOUND
        return operation

    def _next_operation_exists(self) -> bool:
        return self._next_operation_result().is_existent()

    def _next_operation_is_terminal_checkpoint(self) -> bool:
        result = self._next_operation_result()
        return (
            result.is_succeeded()
            or result.is_failed()
            or result.is_cancelled()
            or result.is_stopped()
            or result.is_timed_out()
        )

    @contextmanager
    def _replay_aware(self, *, executes_user_code: bool = False):
        """Update this context's replay status around one durable operation."""
        was_replaying = self.is_replaying()
        next_exists = was_replaying and self._next_operation_exists()
        next_terminal = was_replaying and self._next_operation_is_terminal_checkpoint()
        flip_after = (
            was_replaying
            and not executes_user_code
            and next_exists
            and not next_terminal
        )

        if was_replaying and (
            not next_exists or (executes_user_code and not next_terminal)
        ):
            self._set_replay_status_new()

        try:
            yield
        finally:
            if flip_after:
                self._set_replay_status_new()
            elif self.is_replaying() and not self._next_operation_exists():
                self._set_replay_status_new()


async def _run_in_child_context_in_context(
    context: DurableContext,
    func: Callable[[], Awaitable[T]],
    name: str | None = None,
    *,
    serdes: SerDes | None = None,
    item_serdes: SerDes | None = None,
    summary_generator: SummaryGenerator | None = None,
    is_virtual: bool = False,
) -> T:
    assert_async_callable(func)
    step_name = name if name is not None else getattr(func, "__name__", None)
    with context._replay_aware():
        operation_id = context.step_counter.create_step_id()

        child_context = context.create_child_context(
            operation_id=operation_id,
            is_virtual=is_virtual,
        )

        async def callable_with_child_context():
            return await invoke_user_callable(
                child_context,
                func,
            )

        return await child_handler(
            func=callable_with_child_context,
            state=context.execution_state,
            operation_identifier=OperationIdentifier(
                operation_id=operation_id,
                sub_type=OperationSubType.RUN_IN_CHILD_CONTEXT,
                parent_id=context.parent_id,
                name=step_name,
            ),
            serdes=serdes,
            item_serdes=item_serdes,
            summary_generator=summary_generator,
            is_virtual=is_virtual,
        )


async def run_in_child_context(
    func: Callable[[], Awaitable[T]],
    *,
    name: str | None = None,
    serdes: SerDes | None = None,
    item_serdes: SerDes | None = None,
    summary_generator: SummaryGenerator | None = None,
    is_virtual: bool = False,
) -> T:
    """Execute a durable sub-workflow inside its own child context.

    Args:
        func: The child context function to execute.
        name: Optional durable operation name.
        serdes: Optional serializer for the child context result.
        item_serdes: Optional serializer for child items used by composed operations.
        summary_generator: Optional summary generator for large child results.
        is_virtual: Whether the child context should skip lifecycle checkpoints.
    """
    context = _get_durable_context("run_in_child_context")
    return await _run_in_child_context_in_context(
        context,
        func=func,
        name=name,
        serdes=serdes,
        item_serdes=item_serdes,
        summary_generator=summary_generator,
        is_virtual=is_virtual,
    )


def _get_durable_context(operation_name: str | None = None) -> DurableContext:
    current_context = get_current_context()
    if (
        current_context is None
        or not hasattr(current_context, "execution_state")
        or not hasattr(current_context, "operation_identifier")
        or not hasattr(current_context, "step_counter")
        or not hasattr(current_context, "create_child_context")
    ):
        msg = (
            f"{operation_name or 'Durable operations'} can only be used while a durable function or child "
            "context is executing."
        )
        raise RuntimeError(msg)
    return cast(DurableContext, current_context)
